In [3]:
from har_utils.config import FILE_NAME_SUFFIX
from har_utils.data import get_subject
from har_utils.preprocessing import preprocessing_pipeline
df = get_subject(FILE_NAME_SUFFIX[0])
df.head()

,nose_x,nose_y,left_eye_x,left_eye_y,right_eye_x,right_eye_y,left_ear_x,left_ear_y,right_ear_x,right_ear_y,...,right_hip_y,left_knee_x,left_knee_y,right_knee_x,right_knee_y,left_ankle_x,left_ankle_y,right_ankle_x,right_ankle_y,Action Label
frame_id,,,,,,,,,,,,,,,,,,,,,
0,624.0,258.25,628.0,249.50,625.0,249.750,650.5,252.250,667.5,249.125,...,441.00,656.5,535.0,724.0,528.0,634.5,616.5,746.5,612.0,Walking
1,618.0,260.00,621.5,251.25,618.5,251.625,644.0,254.375,660.5,251.125,...,440.00,651.0,533.5,720.0,526.5,627.5,616.0,746.0,610.5,Walking
2,611.5,260.50,615.0,252.00,613.0,252.250,637.0,256.000,656.5,252.625,...,441.00,644.5,533.0,715.5,525.5,625.5,616.5,746.0,609.5,Walking
3,604.0,261.00,608.0,252.50,605.5,252.750,630.5,256.000,648.5,252.875,...,443.00,639.0,535.0,710.5,525.5,623.0,618.0,745.5,608.0,Walking
4,598.0,260.00,602.5,252.00,600.0,252.000,623.0,256.750,642.5,253.125,...,444.25,634.5,539.0,703.0,525.5,620.5,619.0,742.5,605.5,Walking

In [4]:
from har_utils.features import add_velocity_features

df_mod = add_velocity_features(df)
df_mod.head()

,nose_x,nose_y,left_eye_x,left_eye_y,right_eye_x,right_eye_y,left_ear_x,left_ear_y,right_ear_x,right_ear_y,...,right_hip_x_vel,right_hip_y_vel,left_knee_x_vel,left_knee_y_vel,right_knee_x_vel,right_knee_y_vel,left_ankle_x_vel,left_ankle_y_vel,right_ankle_x_vel,right_ankle_y_vel
frame_id,,,,,,,,,,,,,,,,,,,,,
0,624.0,258.25,628.0,249.50,625.0,249.750,650.5,252.250,667.5,249.125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,618.0,260.00,621.5,251.25,618.5,251.625,644.0,254.375,660.5,251.125,...,-6.0,-1.00,-5.5,-1.5,-4.0,-1.5,-7.0,-0.5,-0.5,-1.5
2,611.5,260.50,615.0,252.00,613.0,252.250,637.0,256.000,656.5,252.625,...,-8.0,1.00,-6.5,-0.5,-4.5,-1.0,-2.0,0.5,0.0,-1.0
3,604.0,261.00,608.0,252.50,605.5,252.750,630.5,256.000,648.5,252.875,...,-7.5,2.00,-5.5,2.0,-5.0,0.0,-2.5,1.5,-0.5,-1.5
4,598.0,260.00,602.5,252.00,600.0,252.000,623.0,256.750,642.5,253.125,...,-8.5,1.25,-4.5,4.0,-7.5,0.0,-2.5,1.0,-3.0,-2.5

In [7]:
df_norm = preprocessing_pipeline(df)
df_norm['Action Label'].value_counts()

y hip corrected
Total Number of Bad Frames where shoulder widht was less than 10: 1377

Action Label
Eating snacks      14730
Sitting quietly    14310
Walking            13721
Using phone        10968
Biting              5610
Throwing things     4377
Attacking           4147
Head banging        3810
Name: count, dtype: int64